export type CareerDiscoverySource = "google" | "facebook" | "instagram" | "linkedin" | "tiktok" | "youtube" | "recommendation" | "client_or_partner" | "creativa_poeta_team" | "event" | "school" | "job_platform" | "article_or_website" | "other";

type CareerCopy = {
  eyebrow: string; title: string; lead: string; primaryCta: string; secondaryCta: string;
  statOne: string; statTwo: string; statThree: string;
  referralEyebrow: string; referralTitle: string; referralLead: string; referralNote: string; referralCta: string;
  openTitle: string; openLead: string; noJobsTitle: string; noJobsLead: string; apply: string; details: string;
  remote: string; deadline: string; responsibilities: string; requirements: string; benefits: string;
  formEyebrow: string; spontaneousTitle: string; jobFormTitle: string; formLead: string;
  labels: Record<string, string>; messagePlaceholder: string; cvHint: string; cvSelected: string;
  discoveryOptions: Array<{ value: CareerDiscoverySource; label: string }>;
  contactError: string; consent: string; submit: string; submitting: string; success: string; error: string;
  types: Record<string, string>;
};

const careerLocale: Record<"fr" | "en" | "nl" | "kiny", CareerCopy> = {
  fr: {
    eyebrow: "Carrières & opportunités", title: "Construisons quelque chose d’utile, ensemble.", lead: "Découvrez les opportunités ouvertes chez Creativa Poeta et les différentes manières de collaborer avec nous.", primaryCta: "Voir les opportunités", secondaryCta: "Candidature spontanée",
    statOne: "Travail flexible", statTwo: "Projets internationaux", statThree: "Compétences concrètes",
    referralEyebrow: "Opportunité active", referralTitle: "Devenez apporteur de clients", referralLead: "Vous connaissez une personne ou une entreprise qui a besoin de services numériques ? Faites la mise en relation. Creativa Poeta réalise le projet et vous recevez normalement 10 % du revenu admissible encaissé.", referralNote: "Une activité indépendante et flexible — ce programme n’est pas un contrat de travail.", referralCta: "Découvrir le programme",
    openTitle: "Postes ouverts", openLead: "Découvrez les missions, stages, contrats et autres opportunités actuellement disponibles.", noJobsTitle: "Vous n’avez pas trouvé le poste que vous cherchiez ?", noJobsLead: "Pas de problème ! Vous pouvez tout de même nous présenter votre profil. Nous conservons les candidatures pertinentes pour de futures missions ou ouvertures.", apply: "Postuler", details: "Voir les détails", remote: "À distance", deadline: "Date limite", responsibilities: "Responsabilités", requirements: "Profil recherché", benefits: "Ce que nous proposons",
    formEyebrow: "Votre profil", spontaneousTitle: "Envoyer une candidature spontanée", jobFormTitle: "Postuler à cette opportunité", formLead: "Présentez-nous votre profil en quelques minutes. Vous pouvez joindre votre CV si vous le souhaitez.",
    labels: { fullName: "Nom complet", email: "E-mail", phone: "Téléphone / WhatsApp", country: "Pays ou ville", desiredRole: "Poste", skills: "Compétences principales", availability: "Disponibilité", cv: "CV", discoverySource: "Comment avez-vous connu Creativa Poeta ?", discoveryOther: "Précisez comment vous nous avez connus", message: "Autres informations" },
    messagePlaceholder: "Par exemple : lien LinkedIn, portfolio, message, motivation, disponibilité ou toute autre information utile.", cvHint: "PDF, DOC ou DOCX — 4 Mo maximum.", cvSelected: "Fichier sélectionné",
    discoveryOptions: [{ value: "google", label: "Google ou un autre moteur de recherche" }, { value: "facebook", label: "Facebook" }, { value: "instagram", label: "Instagram" }, { value: "linkedin", label: "LinkedIn" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }, { value: "recommendation", label: "Recommandation d’un proche" }, { value: "client_or_partner", label: "Client, partenaire ou contact professionnel" }, { value: "creativa_poeta_team", label: "Un membre de Creativa Poeta" }, { value: "event", label: "Événement, conférence ou rencontre" }, { value: "school", label: "École ou université" }, { value: "job_platform", label: "Plateforme d’emploi" }, { value: "article_or_website", label: "Article ou autre site web" }, { value: "other", label: "Autre" }],
    contactError: "Indiquez au moins un moyen de contact : e-mail ou téléphone/WhatsApp.", consent: "J’accepte que Creativa Poeta conserve et utilise ces informations pour étudier ma candidature et me contacter.", submit: "Envoyer ma candidature", submitting: "Envoi…", success: "Votre candidature a bien été enregistrée.", error: "Impossible d’envoyer la candidature.",
    types: { fulltime: "Temps plein", parttime: "Temps partiel", internship: "Stage", contract: "Mission / contrat" },
  },
  en: {
    eyebrow: "Careers & opportunities", title: "Let’s build something useful, together.", lead: "Explore open opportunities at Creativa Poeta and the different ways you can work with us.", primaryCta: "View opportunities", secondaryCta: "Spontaneous application",
    statOne: "Flexible work", statTwo: "International projects", statThree: "Practical skills",
    referralEyebrow: "Active opportunity", referralTitle: "Become a client introducer", referralLead: "Know a person or business that needs digital services? Make the introduction. Creativa Poeta delivers the project and you normally receive 10% of eligible revenue collected.", referralNote: "A flexible independent activity — this program is not an employment contract.", referralCta: "Explore the program",
    openTitle: "Open positions", openLead: "Explore the assignments, internships, contracts and other opportunities currently available.", noJobsTitle: "Didn't find the position you were looking for?", noJobsLead: "No problem! You can still introduce your profile. We keep relevant applications for future assignments or openings.", apply: "Apply", details: "View details", remote: "Remote", deadline: "Deadline", responsibilities: "Responsibilities", requirements: "What we’re looking for", benefits: "What we offer",
    formEyebrow: "Your profile", spontaneousTitle: "Send a spontaneous application", jobFormTitle: "Apply for this opportunity", formLead: "Introduce your profile in a few minutes. You may attach your resume if you wish.",
    labels: { fullName: "Full name", email: "Email", phone: "Phone / WhatsApp", country: "Country or city", desiredRole: "Position", skills: "Main skills", availability: "Availability", cv: "Resume", discoverySource: "How did you hear about Creativa Poeta?", discoveryOther: "Tell us how you found us", message: "Additional information" },
    messagePlaceholder: "For example: LinkedIn link, portfolio, message, motivation, availability or any other useful information.", cvHint: "PDF, DOC or DOCX — maximum 4 MB.", cvSelected: "Selected file",
    discoveryOptions: [{ value: "google", label: "Google or another search engine" }, { value: "facebook", label: "Facebook" }, { value: "instagram", label: "Instagram" }, { value: "linkedin", label: "LinkedIn" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }, { value: "recommendation", label: "Recommendation from a friend or relative" }, { value: "client_or_partner", label: "Client, partner or professional contact" }, { value: "creativa_poeta_team", label: "A Creativa Poeta team member" }, { value: "event", label: "Event, conference or meeting" }, { value: "school", label: "School or university" }, { value: "job_platform", label: "Job platform" }, { value: "article_or_website", label: "Article or another website" }, { value: "other", label: "Other" }],
    contactError: "Provide at least one contact method: email or phone/WhatsApp.", consent: "I agree that Creativa Poeta may store and use this information to review my application and contact me.", submit: "Send my application", submitting: "Sending…", success: "Your application has been recorded.", error: "Unable to send the application.",
    types: { fulltime: "Full time", parttime: "Part time", internship: "Internship", contract: "Contract / assignment" },
  },
  nl: {
    eyebrow: "Carrière & kansen", title: "Laten we samen iets nuttigs bouwen.", lead: "Ontdek de openstaande kansen bij Creativa Poeta en de verschillende manieren om met ons samen te werken.", primaryCta: "Bekijk kansen", secondaryCta: "Spontaan solliciteren",
    statOne: "Flexibel werk", statTwo: "Internationale projecten", statThree: "Praktische vaardigheden",
    referralEyebrow: "Actieve kans", referralTitle: "Word klantenaanbrenger", referralLead: "Kent u een persoon of bedrijf dat digitale diensten nodig heeft? Breng ons met elkaar in contact. Creativa Poeta voert het project uit en u ontvangt normaal 10% van de geïnde, in aanmerking komende omzet.", referralNote: "Een flexibele zelfstandige activiteit — dit programma is geen arbeidsovereenkomst.", referralCta: "Ontdek het programma",
    openTitle: "Openstaande functies", openLead: "Ontdek de opdrachten, stages, contracten en andere kansen die momenteel beschikbaar zijn.", noJobsTitle: "Niet gevonden wat u zocht?", noJobsLead: "Geen probleem! U kunt uw profiel nog steeds insturen. We bewaren relevante sollicitaties voor toekomstige opdrachten of vacatures.", apply: "Solliciteren", details: "Details bekijken", remote: "Op afstand", deadline: "Deadline", responsibilities: "Verantwoordelijkheden", requirements: "Wie we zoeken", benefits: "Wat we bieden",
    formEyebrow: "Uw profiel", spontaneousTitle: "Stuur een spontane sollicitatie", jobFormTitle: "Solliciteer voor deze kans", formLead: "Stel uw profiel in enkele minuten voor. U kunt desgewenst uw cv toevoegen.",
    labels: { fullName: "Volledige naam", email: "E-mail", phone: "Telefoon / WhatsApp", country: "Land of stad", desiredRole: "Functie", skills: "Belangrijkste vaardigheden", availability: "Beschikbaarheid", cv: "Cv", discoverySource: "Hoe heeft u Creativa Poeta leren kennen?", discoveryOther: "Vertel hoe u ons heeft gevonden", message: "Aanvullende informatie" },
    messagePlaceholder: "Bijvoorbeeld: LinkedIn-link, portfolio, bericht, motivatie, beschikbaarheid of andere nuttige informatie.", cvHint: "PDF, DOC of DOCX — maximaal 4 MB.", cvSelected: "Geselecteerd bestand",
    discoveryOptions: [{ value: "google", label: "Google of een andere zoekmachine" }, { value: "facebook", label: "Facebook" }, { value: "instagram", label: "Instagram" }, { value: "linkedin", label: "LinkedIn" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }, { value: "recommendation", label: "Aanbeveling van een vriend of familielid" }, { value: "client_or_partner", label: "Klant, partner of professioneel contact" }, { value: "creativa_poeta_team", label: "Een medewerker van Creativa Poeta" }, { value: "event", label: "Evenement, conferentie of ontmoeting" }, { value: "school", label: "School of universiteit" }, { value: "job_platform", label: "Vacatureplatform" }, { value: "article_or_website", label: "Artikel of andere website" }, { value: "other", label: "Andere" }],
    contactError: "Geef minstens één contactmethode op: e-mail of telefoon/WhatsApp.", consent: "Ik ga ermee akkoord dat Creativa Poeta deze gegevens bewaart en gebruikt om mijn sollicitatie te beoordelen en contact met mij op te nemen.", submit: "Mijn sollicitatie versturen", submitting: "Verzenden…", success: "Uw sollicitatie is geregistreerd.", error: "De sollicitatie kon niet worden verzonden.",
    types: { fulltime: "Voltijds", parttime: "Deeltijds", internship: "Stage", contract: "Contract / opdracht" },
  },
  kiny: {
    eyebrow: "Career & opportunities", title: "Dufatanye gukora ikintu gifite akamaro.", lead: "Reba opportunities ziri kuri Creativa Poeta n’uburyo butandukanye bwo gukorana natwe.", primaryCta: "Reba opportunities", secondaryCta: "Ohereza application",
    statOne: "Flexible work", statTwo: "International projects", statThree: "Practical skills",
    referralEyebrow: "Opportunity ihari", referralTitle: "Ba client introducer", referralLead: "Uzi umuntu cyangwa business ikeneye digital services? Muduhuze. Creativa Poeta ikora project, nawe ugahabwa 10% by’amafaranga yemerewe yakiriwe.", referralNote: "Ni independent flexible activity — si employment contract.", referralCta: "Menya iyi program",
    openTitle: "Imyanya ihari", openLead: "Reba missions, internships, contracts n’izindi opportunities zihari ubu.", noJobsTitle: "Ntiwabonye umwanya washakaga?", noJobsLead: "Nta kibazo! Ushobora gukomeza kutwoherereza profile yawe. Tubika applications zifite relevance ku mirimo izaza.", apply: "Ohereza application", details: "Reba details", remote: "Remote", deadline: "Deadline", responsibilities: "Responsibilities", requirements: "Ibyo dushaka", benefits: "Ibyo dutanga",
    formEyebrow: "Profile yawe", spontaneousTitle: "Ohereza spontaneous application", jobFormTitle: "Saba iyi opportunity", formLead: "Tumenyeshe profile yawe mu minota mike. Ushobora kongeraho CV niba ubishaka.",
    labels: { fullName: "Amazina yose", email: "Email", phone: "Telefone / WhatsApp", country: "Igihugu cyangwa umujyi", desiredRole: "Poste", skills: "Main skills", availability: "Availability", cv: "CV", discoverySource: "Wamenye ute Creativa Poeta?", discoveryOther: "Vuga uko watumenye", message: "Andi makuru" },
    messagePlaceholder: "Urugero: LinkedIn link, portfolio, message, motivation, availability cyangwa andi makuru.", cvHint: "PDF, DOC cyangwa DOCX — ntibirenge 4 MB.", cvSelected: "File wahisemo",
    discoveryOptions: [{ value: "google", label: "Google cyangwa indi search engine" }, { value: "facebook", label: "Facebook" }, { value: "instagram", label: "Instagram" }, { value: "linkedin", label: "LinkedIn" }, { value: "tiktok", label: "TikTok" }, { value: "youtube", label: "YouTube" }, { value: "recommendation", label: "Recommendation y’inshuti cyangwa umuryango" }, { value: "client_or_partner", label: "Client, partner cyangwa professional contact" }, { value: "creativa_poeta_team", label: "Umuntu wo muri Creativa Poeta" }, { value: "event", label: "Event, conference cyangwa meeting" }, { value: "school", label: "School cyangwa university" }, { value: "job_platform", label: "Job platform" }, { value: "article_or_website", label: "Article cyangwa indi website" }, { value: "other", label: "Other" }],
    contactError: "Tanga nibura email cyangwa telefone/WhatsApp.", consent: "Nemeye ko Creativa Poeta ibika kandi ikoresha aya makuru kugira ngo irebe application yanjye kandi imvugishe.", submit: "Ohereza application", submitting: "Birimo koherezwa…", success: "Application yawe yabitswe.", error: "Application ntiyoherejwe.",
    types: { fulltime: "Full time", parttime: "Part time", internship: "Internship", contract: "Contract / mission" },
  },
};

export default careerLocale;
