type CareerCopy = {
  eyebrow: string; title: string; lead: string; primaryCta: string; secondaryCta: string;
  statOne: string; statTwo: string; statThree: string;
  referralEyebrow: string; referralTitle: string; referralLead: string; referralNote: string; referralCta: string;
  openTitle: string; openLead: string; noJobsTitle: string; noJobsLead: string; apply: string; details: string;
  remote: string; deadline: string; responsibilities: string; requirements: string; benefits: string;
  formEyebrow: string; spontaneousTitle: string; jobFormTitle: string; formLead: string;
  labels: Record<string, string>; contactError: string; consent: string; submit: string; submitting: string; success: string; error: string;
  types: Record<string, string>;
};

const careerLocale: Record<"fr" | "en" | "nl" | "kiny", CareerCopy> = {
  fr: {
    eyebrow: "Carrières & opportunités", title: "Construisons quelque chose d’utile, ensemble.", lead: "Découvrez les opportunités ouvertes chez Creativa Poeta, développez votre réseau comme apporteur de clients ou envoyez une candidature spontanée.", primaryCta: "Voir les opportunités", secondaryCta: "Candidature spontanée",
    statOne: "Travail flexible", statTwo: "Projets internationaux", statThree: "Compétences concrètes",
    referralEyebrow: "Opportunité active", referralTitle: "Devenez apporteur de clients", referralLead: "Vous connaissez une personne ou une entreprise qui a besoin de services numériques ? Faites la mise en relation. Creativa Poeta réalise le projet et vous recevez normalement 10 % du revenu admissible encaissé.", referralNote: "Activité indépendante et flexible — ce programme n’est pas un contrat d’emploi salarié.", referralCta: "Découvrir le programme",
    openTitle: "Postes ouverts", openLead: "Les offres publiées depuis le dashboard apparaissent automatiquement ici.", noJobsTitle: "Aucun poste salarié ouvert actuellement", noJobsLead: "Cela ne vous empêche pas de nous présenter votre profil. Nous conservons les candidatures pertinentes pour de futures missions ou ouvertures.", apply: "Postuler", details: "Voir les détails", remote: "À distance", deadline: "Date limite", responsibilities: "Responsabilités", requirements: "Profil recherché", benefits: "Ce que nous proposons",
    formEyebrow: "Votre profil", spontaneousTitle: "Envoyer une candidature spontanée", jobFormTitle: "Postuler à cette opportunité", formLead: "Un formulaire court et utile. Ajoutez un lien vers votre CV, portfolio ou LinkedIn si vous en avez un.",
    labels: { fullName: "Nom complet", email: "E-mail (facultatif)", phone: "Téléphone / WhatsApp (facultatif)", country: "Pays ou ville", desiredRole: "Métier ou rôle recherché", experience: "Expérience", skills: "Compétences principales", linkedin: "LinkedIn (facultatif)", portfolio: "CV ou portfolio — lien (facultatif)", availability: "Disponibilité (facultatif)", message: "Message (facultatif)" }, contactError: "Indiquez au moins un moyen de contact : e-mail ou téléphone/WhatsApp.", consent: "J’accepte que Creativa Poeta conserve et utilise ces informations pour étudier ma candidature et me contacter.", submit: "Envoyer ma candidature", submitting: "Envoi…", success: "Votre candidature a bien été enregistrée.", error: "Impossible d’envoyer la candidature.",
    types: { fulltime: "Temps plein", parttime: "Temps partiel", internship: "Stage", contract: "Mission / contrat" },
  },
  en: {
    eyebrow: "Careers & opportunities", title: "Let’s build something useful, together.", lead: "Explore open opportunities at Creativa Poeta, grow your network as a client introducer, or send a spontaneous application.", primaryCta: "View opportunities", secondaryCta: "Spontaneous application",
    statOne: "Flexible work", statTwo: "International projects", statThree: "Practical skills",
    referralEyebrow: "Active opportunity", referralTitle: "Become a client introducer", referralLead: "Know a person or business that needs digital services? Make the introduction. Creativa Poeta delivers the project and you normally receive 10% of eligible revenue collected.", referralNote: "A flexible independent activity — this program is not an employment contract.", referralCta: "Explore the program",
    openTitle: "Open positions", openLead: "Opportunities published from the dashboard appear here automatically.", noJobsTitle: "No salaried position is open right now", noJobsLead: "You can still introduce your profile. We keep relevant applications for future assignments or openings.", apply: "Apply", details: "View details", remote: "Remote", deadline: "Deadline", responsibilities: "Responsibilities", requirements: "What we’re looking for", benefits: "What we offer",
    formEyebrow: "Your profile", spontaneousTitle: "Send a spontaneous application", jobFormTitle: "Apply for this opportunity", formLead: "A short, useful form. Add a link to your resume, portfolio or LinkedIn profile if available.",
    labels: { fullName: "Full name", email: "Email (optional)", phone: "Phone / WhatsApp (optional)", country: "Country or city", desiredRole: "Desired role", experience: "Experience", skills: "Main skills", linkedin: "LinkedIn (optional)", portfolio: "Resume or portfolio — link (optional)", availability: "Availability (optional)", message: "Message (optional)" }, contactError: "Provide at least one contact method: email or phone/WhatsApp.", consent: "I agree that Creativa Poeta may store and use this information to review my application and contact me.", submit: "Send my application", submitting: "Sending…", success: "Your application has been recorded.", error: "Unable to send the application.",
    types: { fulltime: "Full time", parttime: "Part time", internship: "Internship", contract: "Contract / assignment" },
  },
  nl: {
    eyebrow: "Carrière & kansen", title: "Laten we samen iets nuttigs bouwen.", lead: "Bekijk openstaande kansen bij Creativa Poeta, bouw uw netwerk uit als klantenaanbrenger of stuur een spontane sollicitatie.", primaryCta: "Bekijk kansen", secondaryCta: "Spontaan solliciteren",
    statOne: "Flexibel werk", statTwo: "Internationale projecten", statThree: "Praktische vaardigheden",
    referralEyebrow: "Actieve kans", referralTitle: "Word klantenaanbrenger", referralLead: "Kent u een persoon of bedrijf dat digitale diensten nodig heeft? Breng ons met elkaar in contact. Creativa Poeta voert het project uit en u ontvangt normaal 10% van de geïnde, in aanmerking komende omzet.", referralNote: "Een flexibele zelfstandige activiteit — dit programma is geen arbeidsovereenkomst.", referralCta: "Ontdek het programma",
    openTitle: "Openstaande functies", openLead: "Aanbiedingen die via het dashboard worden gepubliceerd verschijnen hier automatisch.", noJobsTitle: "Momenteel geen openstaande functie in loondienst", noJobsLead: "U kunt uw profiel nog steeds insturen. We bewaren relevante sollicitaties voor toekomstige opdrachten of vacatures.", apply: "Solliciteren", details: "Details bekijken", remote: "Op afstand", deadline: "Deadline", responsibilities: "Verantwoordelijkheden", requirements: "Wie we zoeken", benefits: "Wat we bieden",
    formEyebrow: "Uw profiel", spontaneousTitle: "Stuur een spontane sollicitatie", jobFormTitle: "Solliciteer voor deze kans", formLead: "Een kort en nuttig formulier. Voeg indien mogelijk een link toe naar uw cv, portfolio of LinkedIn-profiel.",
    labels: { fullName: "Volledige naam", email: "E-mail (optioneel)", phone: "Telefoon / WhatsApp (optioneel)", country: "Land of stad", desiredRole: "Gewenste rol", experience: "Ervaring", skills: "Belangrijkste vaardigheden", linkedin: "LinkedIn (optioneel)", portfolio: "Cv of portfolio — link (optioneel)", availability: "Beschikbaarheid (optioneel)", message: "Bericht (optioneel)" }, contactError: "Geef minstens één contactmethode op: e-mail of telefoon/WhatsApp.", consent: "Ik ga ermee akkoord dat Creativa Poeta deze gegevens bewaart en gebruikt om mijn sollicitatie te beoordelen en contact met mij op te nemen.", submit: "Mijn sollicitatie versturen", submitting: "Verzenden…", success: "Uw sollicitatie is geregistreerd.", error: "De sollicitatie kon niet worden verzonden.",
    types: { fulltime: "Voltijds", parttime: "Deeltijds", internship: "Stage", contract: "Contract / opdracht" },
  },
  kiny: {
    eyebrow: "Career & opportunities", title: "Dufatanye gukora ikintu gifite akamaro.", lead: "Reba opportunities ziri kuri Creativa Poeta, ukore nka client introducer cyangwa wohereze spontaneous application.", primaryCta: "Reba opportunities", secondaryCta: "Ohereza application",
    statOne: "Flexible work", statTwo: "International projects", statThree: "Practical skills",
    referralEyebrow: "Opportunity ihari", referralTitle: "Ba client introducer", referralLead: "Uzi umuntu cyangwa business ikeneye digital services? Muduhuze. Creativa Poeta ikora project, nawe ugahabwa 10% by’amafaranga yemerewe yakiriwe.", referralNote: "Ni independent flexible activity — si employment contract.", referralCta: "Menya iyi program",
    openTitle: "Imyanya ihari", openLead: "Jobs zapublishijwe muri dashboard zigaragara hano automatically.", noJobsTitle: "Nta salaried position ihari ubu", noJobsLead: "Ushobora gukomeza kutwoherereza profile yawe. Tubika applications zifite relevance ku mirimo izaza.", apply: "Ohereza application", details: "Reba details", remote: "Remote", deadline: "Deadline", responsibilities: "Responsibilities", requirements: "Ibyo dushaka", benefits: "Ibyo dutanga",
    formEyebrow: "Profile yawe", spontaneousTitle: "Ohereza spontaneous application", jobFormTitle: "Saba iyi opportunity", formLead: "Form ngufi kandi ifite akamaro. Shyiramo link ya CV, portfolio cyangwa LinkedIn niba uyifite.",
    labels: { fullName: "Amazina yose", email: "Email (si ngombwa)", phone: "Telefone / WhatsApp (si ngombwa)", country: "Igihugu cyangwa umujyi", desiredRole: "Role ushaka", experience: "Experience", skills: "Main skills", linkedin: "LinkedIn (si ngombwa)", portfolio: "CV cyangwa portfolio — link", availability: "Availability", message: "Message" }, contactError: "Tanga nibura email cyangwa telefone/WhatsApp.", consent: "Nemeye ko Creativa Poeta ibika kandi ikoresha aya makuru kugira ngo irebe application yanjye kandi imvugishe.", submit: "Ohereza application", submitting: "Birimo koherezwa…", success: "Application yawe yabitswe.", error: "Application ntiyoherejwe.",
    types: { fulltime: "Full time", parttime: "Part time", internship: "Internship", contract: "Contract / mission" },
  },
};

export default careerLocale;
